import type { Incoterm } from '@/types';

export const INCOTERMS: Incoterm[] = [
  { code: 'EXW', name: 'Ex Works', nameDE: 'Ab Werk', description: 'The seller makes goods available at their premises. The buyer bears all transportation costs and risks from that point.', descriptionDE: 'Der Verkäufer stellt die Ware an seinen Geschäftsräumen zur Verfügung. Der Käufer trägt alle Transportkosten und -risiken ab diesem Punkt.', mode: 'any' },
  { code: 'FCA', name: 'Free Carrier', nameDE: 'Frei Frachtführer', description: 'The seller delivers goods to a named carrier or another person nominated by the buyer at the seller\'s premises or another named place.', descriptionDE: 'Der Verkäufer liefert die Ware an einen vom Käufer genannten Frachtführer oder eine andere Person an einem genannten Ort.', mode: 'any' },
  { code: 'CPT', name: 'Carriage Paid To', nameDE: 'Frachtfrei', description: 'The seller delivers goods to a carrier and pays the cost of carriage necessary to bring the goods to the named destination.', descriptionDE: 'Der Verkäufer liefert die Ware an einen Frachtführer und zahlt die Frachtkosten bis zum genannten Bestimmungsort.', mode: 'any' },
  { code: 'CIP', name: 'Carriage and Insurance Paid To', nameDE: 'Frachtfrei versichert', description: 'The seller has the same responsibilities as CPT but also contracts for insurance cover against the buyer\'s risk of loss or damage.', descriptionDE: 'Wie CPT, aber der Verkäufer schließt auch eine Transportversicherung gegen das Risiko des Käufers ab.', mode: 'any' },
  { code: 'DAP', name: 'Delivered at Place', nameDE: 'Geliefert benannter Ort', description: 'The seller delivers when goods are placed at the disposal of the buyer on the arriving means of transport ready for unloading at the named place.', descriptionDE: 'Der Verkäufer liefert, wenn die Ware dem Käufer auf dem ankommenden Beförderungsmittel entladebereit zur Verfügung gestellt wird.', mode: 'any' },
  { code: 'DPU', name: 'Delivered at Place Unloaded', nameDE: 'Geliefert entladen', description: 'The seller delivers when goods are unloaded from the arriving means of transport and placed at the disposal of the buyer at a named terminal or place.', descriptionDE: 'Der Verkäufer liefert, wenn die Ware entladen dem Käufer am genannten Terminal oder Ort zur Verfügung gestellt wird.', mode: 'any' },
  { code: 'DDP', name: 'Delivered Duty Paid', nameDE: 'Geliefert verzollt', description: 'The seller delivers the goods when placed at the disposal of the buyer, cleared for import and not unloaded from any means of transport at the named place of destination.', descriptionDE: 'Der Verkäufer liefert die Ware verzollt am genannten Bestimmungsort und trägt alle Kosten einschließlich Einfuhrzölle.', mode: 'any' },
  { code: 'FAS', name: 'Free Alongside Ship', nameDE: 'Frei Längsseite Schiff', description: 'The seller delivers when goods are placed alongside the vessel nominated by the buyer at the named port of shipment.', descriptionDE: 'Der Verkäufer liefert, wenn die Ware längsseits des vom Käufer genannten Schiffes am genannten Verschiffungshafen gestellt ist.', mode: 'sea' },
  { code: 'FOB', name: 'Free On Board', nameDE: 'Frei an Bord', description: 'The seller delivers when goods are loaded on board the vessel nominated by the buyer at the named port of shipment.', descriptionDE: 'Der Verkäufer liefert, wenn die Ware an Bord des vom Käufer genannten Schiffes am genannten Verschiffungshafen geladen ist.', mode: 'sea' },
  { code: 'CFR', name: 'Cost and Freight', nameDE: 'Kosten und Fracht', description: 'The seller delivers goods on board the vessel and pays costs and freight necessary to bring goods to the named port of destination.', descriptionDE: 'Der Verkäufer liefert an Bord des Schiffes und zahlt Kosten und Fracht bis zum genannten Bestimmungshafen.', mode: 'sea' },
  { code: 'CIF', name: 'Cost, Insurance and Freight', nameDE: 'Kosten, Versicherung und Fracht', description: 'The seller has the same responsibilities as CFR but also contracts for insurance cover against the buyer\'s risk of loss or damage.', descriptionDE: 'Wie CFR, aber der Verkäufer schließt auch eine Transportversicherung gegen das Risiko des Käufers ab.', mode: 'sea' },
];
